export const portalTestIds = {
  profileFieldFirstName: 'profile-field-first-name',
  profileFieldLastName: 'profile-field-last-name',
  profileFieldDob: 'profile-field-dob',
  profileFieldPhone: 'profile-field-phone',
  profileFieldEmail: 'profile-field-email',
  profileFieldSex: (value) => (
    `profile-field-sex-${String(value ?? '').toLowerCase()}`
  ),
  profileFieldLanguage: (value) => (
    `profile-field-language-${String(value ?? '').toLowerCase()}`
  ),
  profileFieldComm: (value) => (
    `profile-field-comm-${String(value ?? '')
      .toLowerCase()
      .replace(/_/g, '-')}`
  ),
  profileFieldAddressLine1: 'profile-field-address-line1',
  profileFieldAddressLine2: 'profile-field-address-line2',
  profileFieldCity: 'profile-field-city',
  profileFieldState: 'profile-field-state',
  profileFieldZip: 'profile-field-zip',
  profileFieldEmergencyFirst: 'profile-field-emergency-first',
  profileFieldEmergencyLast: 'profile-field-emergency-last',
  profileFieldEmergencyRel: 'profile-field-emergency-rel',
  profileFieldEmergencyPhone: 'profile-field-emergency-phone',
  profileFieldInsurancePayer: 'profile-field-insurance-payer',
  profileFieldInsuranceMember: 'profile-field-insurance-member',
  profileFieldInsuranceFrom: 'profile-field-insurance-from',
  profileFieldInsuranceTo: 'profile-field-insurance-to',
  profileNoAllergies: 'profile-no-allergies',
  profileBtnAddAllergy: 'profile-btn-add-allergy',
  profileAllergyName: (index) => `profile-allergy-name-${index}`,
  profileAllergySeverity: (index) => (
    `profile-allergy-severity-${index}`
  ),
  profileAllergyRemove: (index) => (
    `profile-allergy-remove-${index}`
  ),
  profileBtnSave: 'profile-btn-save',
  dashboardCompleteProfile: 'dashboard-btn-complete-profile',
  dashboardNextAppointment: 'dashboard-next-appointment',
  dashboardRequests: 'dashboard-appointment-requests',
  dashboardScheduled: 'dashboard-appointments-scheduled',
  dashboardConsents: 'dashboard-pending-consents',
  dashboardDocuments: 'dashboard-documents',
  dashboardViewMore: (section) => (
    `dashboard-btn-view-more-${section}`
  ),
  dashboardJoin: (id) => `dashboard-btn-join-${id}`,
  dashboardKpiScheduled: 'dashboard-kpi-scheduled',
  dashboardKpiRequests: 'dashboard-kpi-requests',
  dashboardKpiDocuments: 'dashboard-kpi-documents',
  dashboardKpiConsents: 'dashboard-kpi-consents',
  dashboardTasks: 'dashboard-tasks',
  dashboardTaskProfile: 'dashboard-task-profile',
  dashboardTaskConsent: (id) => `dashboard-task-consent-${id}`,
  dashboardQuickActions: 'dashboard-quick-actions',
  dashboardQuickBook: 'dashboard-quick-book',
  dashboardQuickDocuments: 'dashboard-quick-documents',
  dashboardQuickConsents: 'dashboard-quick-consents',
  dashboardQuickMessage: 'dashboard-quick-message',
  dashboardQuickProfile: 'dashboard-quick-profile',
  dashboardQuickSettings: 'dashboard-quick-settings',
  headerNotifications: 'header-notifications',
  headerContactSupport: 'header-contact-support',
  navDashboard: 'nav-dashboard',
  navAppointments: 'nav-appointments',
  navDocuments: 'nav-documents',
  navConsents: 'nav-consents',
  navForms: 'nav-forms',
  navProfile: 'nav-profile',
  navSecurity: 'nav-security',
  appointmentsPage: 'appointments-page',
  appointmentsOpenRequests: 'appointments-open-requests',
  appointmentsUpcoming: 'appointments-upcoming',
  appointmentsPast: 'appointments-past',
  appointmentsBtnRequest: 'appointments-btn-request',
  appointmentsRequestDialog: 'appointments-request-dialog',
  appointmentsRequestDialogClose:
    'appointments-request-dialog-close',
  appointmentsRequestDialogCancel:
    'appointments-request-dialog-cancel',
  appointmentsBtnBook: 'appointments-btn-book',
  appointmentsScheduleDialog: 'appointments-schedule-dialog',
  appointmentsScheduleDialogClose:
    'appointments-schedule-dialog-close',
  appointmentsFieldPreferredStart: 'appointments-field-preferred-start',
  appointmentsFieldPreferredTime: 'appointments-field-preferred-time',
  appointmentsFieldNotes: 'appointments-field-notes',
  appointmentsFieldRequestService: 'appointments-field-request-service',
  appointmentsFieldBookService: 'appointments-field-book-service',
  appointmentsBtnSearchSlots: 'appointments-btn-search-slots',
  appointmentsSlot: (index) => `appointments-slot-${index}`,
  appointmentsCancel: (id) => `appointments-btn-cancel-${id}`,
  appointmentsJoin: (id) => `appointments-btn-join-${id}`,
  appointmentsRequestCancel: (id) => (
    `appointments-btn-request-cancel-${id}`
  ),
  bookingWizard: 'booking-wizard',
  bookingService: (id) => `booking-service-${id}`,
  bookingClinicianAny: 'booking-clinician-any',
  bookingClinician: (id) => `booking-clinician-${id}`,
  bookingWhenSoonest: 'booking-when-soonest',
  bookingWhenDay: 'booking-when-day',
  bookingWhenRange: 'booking-when-range',
  bookingFieldDate: 'booking-field-date',
  bookingFieldFromDate: 'booking-field-from-date',
  bookingFieldToDate: 'booking-field-to-date',
  bookingBtnSearchSlots: 'booking-btn-search-slots',
  bookingBtnNextSlots: 'booking-btn-next-slots',
  bookingTab: (period) => `booking-tab-${String(period).toLowerCase()}`,
  bookingSlot: (startAtUtc) => {
    const slug = String(startAtUtc ?? '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
    return `booking-slot-${slug}`
  },
  bookingFieldNotes: 'booking-field-notes',
  bookingConfirmAccurate: 'booking-confirm-accurate',
  bookingBtnBack: 'booking-btn-back',
  bookingBtnNext: 'booking-btn-next',
  bookingBtnNextClinician: 'booking-btn-next-clinician',
  bookingBtnConfirm: 'booking-btn-confirm',
  bookingBtnAnother: 'booking-btn-another',
  bookingSuccess: 'booking-success',
  selectLocationPage: 'select-location-page',
  selectLocationItem: (id) => `select-location-${id}`,
  headerLocationSwitch: 'header-location-switch',
  headerLocationItem: (id) => `header-location-${id}`,
  headerLocaleSwitch: 'header-locale-switch',
  headerUserMenu: 'header-user-menu',
  headerLogout: 'logout',
  timezoneBanner: 'layout-timezone-banner',
  timezoneBannerMenu: 'layout-timezone-banner-menu',
  timezoneBannerUseDevice: 'layout-timezone-banner-use-device',
  timezoneBannerKeepClinic: 'layout-timezone-banner-keep-clinic',
  timezoneBannerRevert: 'layout-timezone-banner-revert',
  resendVerificationEmail: 'resend-verification-email',
  resendVerificationSubmit: 'resend-verification-submit',
  registerResend: 'register-btn-resend-verification',
  registerFieldLocation: 'register-field-location',
  inviteHasClientRecord: 'invite-has-client-record',
  consentsPage: 'consents-page',
  navMessages: 'nav-messages',
  messagesPage: 'messages-page',
  messagesPanel: 'messages-panel',
  messagesFab: 'messages-fab',
  messagesClose: 'messages-btn-close',
  messagesRefresh: 'messages-btn-refresh',
  messagesBlocked: 'messages-blocked',
  messagesList: 'messages-list',
  messagesItem: (id) => `messages-item-${id}`,
  messagesDay: (key) => `messages-day-${key}`,
  messagesThreadHead: 'messages-thread-head',
  messagesFile: (id) => `messages-file-${id}`,
  messagesFileInput: 'messages-file-input',
  messagesAttach: 'messages-btn-attach',
  messagesInput: 'messages-input',
  messagesSend: 'messages-btn-send',
  messagesUnreadBadge: 'messages-unread-badge',
  consentsBtnOpen: (id) => `consents-btn-open-${id}`,
  consentsSignDialog: 'consents-sign-dialog',
  consentsSignDialogClose: 'consents-sign-dialog-close',
  consentsBtnSign: 'consents-btn-sign',
  consentsBtnDecline: 'consents-btn-decline',
  consentSignatureClear: 'consents-signature-btn-clear',
}

export const telehealthTestIds = {
  lobbyJoin: 'telehealth-lobby-btn-join',
  lobbyBack: 'telehealth-lobby-btn-back',
  lobbyDeviceClose: 'telehealth-lobby-device-btn-close',
  endedComplete: 'telehealth-ended-btn-complete',
  endedLeave: 'telehealth-ended-btn-leave',
  endedBack: 'telehealth-ended-btn-back',
  inCallMute: 'telehealth-incall-btn-mute',
  inCallVideo: 'telehealth-incall-btn-video',
  inCallSpeaker: 'telehealth-incall-btn-speaker',
  inCallScreen: 'telehealth-incall-btn-screen',
  inCallChat: 'telehealth-incall-btn-chat',
  inCallMinimize: 'telehealth-incall-btn-minimize',
  inCallLeave: 'telehealth-incall-btn-leave',
  chatSend: 'telehealth-chat-btn-send',
  chatDelete: (id) => `telehealth-chat-btn-delete-${id}`,
  fileDownload: (id) => `telehealth-file-btn-download-${id}`,
  fileDelete: (id) => `telehealth-file-btn-delete-${id}`,
  waitingLeave: 'telehealth-waiting-btn-leave',
  admit: (id) => `telehealth-btn-admit-${id}`,
  copyInvite: 'telehealth-btn-copy-invite',
  resendInvite: 'telehealth-btn-resend-invite',
}

export const sessionInactivityTestIds = {
  dialog: 'session-inactivity-dialog',
  countdown: 'session-inactivity-countdown',
  closeSection: 'session-inactivity-btn-close-section',
  keepOpen: 'session-inactivity-btn-keep-open',
}
